print("Pasos para verificar 2FA y contraseñas de aplicación:")
print("=" * 50)
print()
print("1. Ve a: https://myaccount.google.com/security")
print("2. Busca la sección 'Signing in to Google'")
print("3. Verifica que '2-Step Verification' esté ON")
print()
print("4. Si 2FA está activado, ve a: https://myaccount.google.com/apppasswords")
print("5. Crea una nueva contraseña de aplicación:")
print("   - Selecciona 'Mail' como aplicación")
print("   - Copia EXACTAMENTE la contraseña que te da (16 caracteres)")
print()
print("6. Alternativamente, puedes ir a:")
print("   - https://myaccount.google.com/")
print("   - Buscar 'App passwords' en la barra de búsqueda")
print()
print("Si 2FA NO está activado:")
print("- Ve a https://myaccount.google.com/security")
print("- Haz clic en '2-Step Verification'")
print("- Sigue los pasos para activarlo")
print("- Luego genera la contraseña de aplicación")
print()
print("Nota: Si usas una cuenta corporativa/trabajo, puede que tengas restricciones.")